### PR TITLE
Update example to traefik v2

### PR DESCRIPTION
**Pull request by darthf1**
Ive updated the following:
- update example to traefik v2
- set specific image tag for traefik
- automatic http to https direction
- merged the multiple examples on this page into one
- removed the part about multiple traefik instances. I don't have this setup so didn't test. You could argue if this should be a part of this example. If you want it back, let me know.
- accidentally updated postgresql tag from 10 to 11. Do you want me to revert this or do you want this updated in the main repo as well? I think 11 is mainstream at the moment?

| Q             | A
| ------------- | ---
| Bug fix?      | no 
| New feature?  | no 
| BC breaks?    | no
| Deprecations? | no
| Tickets       | fixes #... 
| License       | MIT
| Doc PR        | api-platform/docs#953

### CODE REVIEW

**Comment by dunglas** [comment]
Could you take a look @Darkweak @teohhanhui?

**Comment by Darkweak** [comment]
Træfik V2 is on the way, I just don't took time to open PR, then I've done lot of refactoring to configure it with less env vars

**Comment by Darkweak** [comment]
Then this PR doesn't take multiple instances in consideration, I will open my PR this week-end to fix that

**Comment by Darkweak** [comment]
#974

**Comment by soyuka** [comment]
superseeded by #974, thanks @darthf1 !

**Pull request closed without merging**
