### PR TITLE
Admin On REST

### PR DESCRIPTION
**Pull request by mysiar**

### CODE REVIEW

**Comment by dunglas** [comment]
I think it deserves an in depth explanation of how it is better to use `admin` and how it is better to use the generator. And how to switch for the one to the other. Or it will be very confusing for the user to have 2 tools doing the same thing.

**Comment by mysiar** [comment]
OK. I will try to do it more explicit

**Comment by mysiar** [comment]
@dunglas have a look now

**Comment by mauchede** [comment]
As `hydraClient` is needed by `admin-on-rest`, do you think we have to recommend `@api-platform/admin` as dependency?

**Comment by mysiar** [comment]
@mauchede this is actually very good point :)
I will look into it and update docs

**Comment by mysiar** [comment]
The only thing that I do not see in hydraClient is possibility to add auth token

**Comment by mauchede** [comment]
`hydraClient` does not manage authentication token, but `fetchHydra` does. If you wish to define a token, you have to initialize `fetchHydra`:

```js
import { fetchHydra as baseFetchHydra, hydraClient as baseHydraClient } from '@api-platform/admin';

export const fetchHeaders = {
    'Authorization': `Bearer ${window.localStorage.getItem('token')}`,
};

export const fetchHydra = (url, options = {}) => baseFetchHydra(url, {
    ...options,
    headers: new Headers(fetchHeaders),
});

export default api => baseHydraClient(api, fetchHydra);
```

**Comment by mysiar** [comment]
I'm not sure if hydraClient can be used, there is no need to parse anything, resources are generated

**Comment by mysiar** [comment]
Another solution would to take the client out of doucmentation and add it to the templates as util
WDYT?

**Comment by dunglas** [comment]
It needs a rebase.

**Comment by mysiar** [comment]
@dunglas rebase done

**Comment by Simperfit** [comment]
it needs a rebase again

**Comment by mysiar** [comment]
looks like this branch is already to old, should I close it and move doc files to 2.3 instead and create new PR ?

**Comment by mysiar** [comment]
new PR to 2.3 branch

**Pull request closed without merging**
