### PR TITLE
Update getting-started.md - update phpdoc

### PR DESCRIPTION
**Pull request by xElysioN**
Hi,

The phpdoc of the variable $name was [@]param instead of [@]var. (Other variables don't have it, so i decide to remove it)
http://docs.phpdoc.org/references/phpdoc/tags/param.html

And add the phpdoc to removeOffer.

### CODE REVIEW

**Comment by teohhanhui** [comment]
No. I think it's fine the way it is. :smile:

**Comment by dunglas** [comment]
> The phpdoc of the variable $name was [@]param instead of [@]var. (Other variables don't have it, so i decide to remove it)

Good catch, but please keep it (just change `@param` in `@var` because this annotation is used to generate the public documentation.

> And add the phpdoc to removeOffer.

Please remove it (according to our CS). The information is already provided by the typehint and adds nothing.

**Comment by teohhanhui** [comment]
Oops. Yeah, I overlooked the typo lol...

**Comment by xElysioN** [comment]
I remove the annotation in the removeOffer function and change param by var.

**Comment by meyerbaptiste** [comment]
Thanks @xElysioN!

**Pull request merged**
