### PR TITLE
Adding graphql pagination section

### PR DESCRIPTION
**Pull request by Reduxx**
This is the docs PR for the core PR api-platform/core#2142

It adds a pagination section for graphql :)

### CODE REVIEW

**Comment by dunglas** [comment]
I made some minor changes, 👍 for me.

**Comment by dunglas** [comment]
However, it should target master as it's a new feature.

**Comment by Reduxx** [comment]
I changed the target branch and made my branch compatible :)

**Comment by alanpoulain** [comment]
Doc rebased and updated.

**Comment by alanpoulain** [comment]
Thank you @Reduxx.

**Pull request merged**
