### PR TITLE
Update operations.md

### PR DESCRIPTION
**Pull request by lpj145**
I think this help some new members with api platform, please, i'm spend most hours with this. :( :)

### CODE REVIEW

**Comment by dunglas** [comment]
It's because you're using 2.2beta (or Flex?) and the docs are still being updated for this version: #383.

**Comment by lpj145** [comment]
i'm using Flex, i still update documentation because spended long time to work custom actions.

**Comment by Simperfit** [comment]
Is this stil relevant ?

**Comment by dunglas** [comment]
Closing as we don't point to issues in the documentation.

**Pull request closed without merging**
