### PR TITLE
Reduce visibility of FOSUserBundle

### PR DESCRIPTION
**Pull request by teohhanhui**
Don't promote it

### CODE REVIEW

**Comment by dunglas** [comment]
I would prefer to add a warning on the FOSUser integration page than removing this link.

**Comment by teohhanhui** [comment]
I think it's bad to highlight it as one of the "features" of API Platform.

**Comment by teohhanhui** [comment]
Maybe we can move it further down the page?

**Comment by teohhanhui** [comment]
For example, we don't mention NelmioApiDocBundle integration as a feature. We should give FOSUserBundle the same treatment.

**Comment by dunglas** [comment]
Thanks @teohhanhui. It will still appear in the menu so it's good.

**Pull request merged**
