### PR TITLE
Swagger ui config patch

### PR DESCRIPTION
**Pull request by dvc**
related to https://github.com/api-platform/core/issues/3730

### CODE REVIEW

**Comment by alexislefebvre** [comment]
Does it work already or it will require an update in api-platform-core before?

**Comment by dvc** [comment]
@alexislefebvre i think, it's require and update. I'll try to fix it in a couple of days

**Comment by dvc** [comment]
@alexislefebvre, hello! I did it :)

**Comment by alanpoulain** [comment]
Thanks @dvc.

**Pull request merged**
