### PR TITLE
Add a yaml example for specifying an identifier.

### LINKED ISSUE #639: How do you specific an identifier in yaml
The documentation gives an example for defining an identifier with annotations only - https://api-platform.com/docs/core/serialization/#entity-identifier-case

How do you specify an identifier with yaml? I'm happy to update the docs if someone can tell me how to specify it.

### PR DESCRIPTION
**Pull request by trsteel88**
Closes #639

### CODE REVIEW

**Comment by trsteel88** [comment]
Actually, I don't think this is correct. I still get the warning ```Unable to generate an IRI for the item of type \"App\\Api\\Model\\MyNonDoctrineModel\"```

**Comment by antograssiot** [comment]
Do you have a getter on your property and enable the get on item operation ?

**Comment by trsteel88** [comment]
Yes.

```php
final class MyNonDoctrineModel
{
    /**
     * @var string
     */
    private $id;

    /**
     * @var Organisation
     */
    private $organisation;

    /**
     * @var Template
     */
    private $template;

    /**
     * @var float
     */
    private $price;

    public function __construct(Organisation $organisation, Template $template)
    {
        $this->organisation = $organisation;
        $this->template = $template;
        $this->id = $this->organisation->getId().'-'.$this->template->getId();
    }

    public function getId(): string
    {
        return $this->id;
    }
```

**Comment by trsteel88** [comment]
My resource looks like this

```yaml
App\Api\Model\ MyNonDoctrineModel:
    properties:
        identifier: [id]
    attributes:
        access_control: "is_granted('ROLE_USER')"
    itemOperations:
        get:
            method: GET
            path: /organisations-templates/{id}
            defaults:
                _api_receive: false
            controller: App\Api\Action\OrganisationTemplatePrice\ViewAction
    collectionOperations:
        get:
            method: GET
            path: /organisations-templates
            controller: App\Api\Action\OrganisationTemplatePrice\ListAction
```

It's definitely a configuration issue with defining the identifiers because what I have configured are not coming through when I do a dump within IdentifiersExtractor.php

If I override the array of identifiers within that code it works.

**Comment by antograssiot** [comment]
isn't that 
```
App\Api\Model\MyNonDoctrineModel:
    properties:
        id:
            identifier: true
...
```

instead ?

**Comment by trsteel88** [comment]
I'm away from my computer at the moment. But I am pretty sure I tried that
and it didn't work either.

**Comment by trsteel88** [comment]
You were right @antograssiot. Thanks!

**Comment by dunglas** [comment]
Thanks a lot @trsteel88 and @antograssiot, this kind of enhancements in the docs are very helpful!

**Comment by trsteel88** [comment]
You're welcome!

**Pull request merged**
