### PR TITLE
Update security ApiProperty variables

### PR DESCRIPTION
**Pull request by xavren**

### CODE REVIEW

**Comment by alanpoulain** [comment]
Thanks but I think it's better to favor this one: https://github.com/api-platform/docs/pull/1349.

**Comment by xavren** [comment]
Hey @alanpoulain, 

`request` is actually unavailable from variables in this context
`object` is not the current resource during denormalization but the resourceClass

The PR #1349 actually is adding some informations about previous object that is nice but different from this PR, merging this contributions would be nice

**Comment by alanpoulain** [comment]
I didn't see the part about the `request`, sorry.
For the `object`, it will be `null` instead of the resource class when https://github.com/api-platform/core/pull/4184 is merged. But it will be on `main`, so I guess we can merge your PR in the meantime.
I have been too quick, sorry!

**Comment by alanpoulain** [comment]
Is `user` available?

**Comment by xavren** [comment]
Yes, user is there too

**Pull request merged**
