### PR TITLE
fixed broken links

### PR DESCRIPTION
**Pull request by disembarkedone**
fixed links for operations, pagination, filters, content-negotiation

### CODE REVIEW

**Comment by dunglas** [comment]
The change doesn't look good: it breaks the link when you try: https://github.com/api-platform/docs/blob/78c10bc4daf9faf28872122e429e0502250f5ff1/distribution/index.md

Why do you think it should be changed? It's broken on the website?

**Comment by disembarkedone** [comment]
I was afraid it would break elsewhere.

The links I was hoping to fix do not work here: https://api-platform.com/docs/distribution/

**Comment by dunglas** [comment]
Ok, AFAIU it has been introduced by https://github.com/api-platform/website/pull/91. I see no other fixes than reverting this PR and **not** using slashes for such pages. Otherwise the docs will be broken on Github.

ping @raoulclais @Fabious

**Comment by dunglas** [comment]
An alternative fix would be to append `.html` to URLs corresponding to transformed `.md` pages.

**Comment by dunglas** [comment]
Fixed by https://github.com/api-platform/website/pull/93. Thanks for the report and for helping us to debug @disembarkedone!

**Pull request closed without merging**
