### PR TITLE
fix: Some typo on the doc

### PR DESCRIPTION
**Pull request by Gregcop1**

### CODE REVIEW

**Comment by Simperfit** [comment]
Thanks @Gregcop1

**Comment by teohhanhui** [comment]
I'm curious why we don't stick to https://schema.org/Book for this? Is there a good reason?

**Comment by dunglas** [comment]
It was to make it clear that it's not related at all with Schema.org.

**Comment by dunglas** [comment]
@Simperfit this patch should have been merged in 2.0

**Pull request merged**
