### PR TITLE
Update traefik config to api 2.4+

### PR DESCRIPTION
**Pull request by vasilvestre**
I haven't tested the configuration yet

https://github.com/api-platform/docs/issues/793

### CODE REVIEW

**Comment by vasilvestre** [comment]
Should varnish be kept on the traefik config ? @dunglas

**Comment by dunglas** [comment]
I think so @vasilvestre. @Darkweak can you take a look?

**Comment by Darkweak** [comment]
I think we should add config with network to be able to run different traefik (& api-platform including traefik) instances.
Then I'll update this traefik configuration to Traefik V2 to be up to date with it

**Comment by Darkweak** [comment]
https://github.com/api-platform/docs/pull/837/files should close this

**Comment by vasilvestre** [comment]
Closed in favor of #837 :)

**Pull request closed without merging**
