### PR TITLE
docs: Fix broken link kubernetes.md

### PR DESCRIPTION
**Pull request by Lenny4**

### CODE REVIEW

**Comment by Lenny4** [comment]
@alanpoulain here is the new PR for https://github.com/api-platform/docs/pull/1498

**Comment by alanpoulain** [comment]
Could you rebase please? I've fixed the CI.

**Review by dunglas — APPROVED** [review]

**Comment by Lenny4** [comment]
@alanpoulain 

> Could you rebase please? I've fixed the CI.

done.

**Comment by alanpoulain** [comment]
Thanks.

**Pull request merged**
