### PR TITLE
Update the way to add login with jwt token return in swagger. Previous did not work with 2.5

### PR DESCRIPTION
**Pull request by vibby**
Working documentation, for adding custom routes in swagger API.

### CODE REVIEW

**Comment by alanpoulain** [comment]
What was not working before?

**Comment by vibby** [comment]
With the proposed code :
image
(note the emptiness in parameters area)

With my changes :
image
And the Model associated
image

**Comment by alanpoulain** [comment]
I think you are using a recent version of Swagger. Are you on master maybe?
This is what I have:
image

**Comment by vibby** [comment]
Hum, I think I did not set the version of OpenAPI anywhere. I just use api-platform/core on version 2.5.7 out of the box …

**Comment by soyuka** [comment]
Mhh indeed this needs a fix but we should decorate the OpenAPI Factory as stated https://github.com/api-platform/docs/blob/master/core/openapi.md

**Pull request closed without merging**
