### PR TITLE
prevent "Notice: Undefined variable: attributes"

### PR DESCRIPTION
**Pull request by esistgut**

### CODE REVIEW

**Comment by soyuka** [comment]
Code looks correct, I don't get the issue.

**Comment by esistgut** [comment]
I'm not sure about the reason, I'm on
```
$ php --version
PHP 7.2.17-0ubuntu0.19.04.1 (cli) (built: Apr 18 2019 18:01:25) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.17-0ubuntu0.19.04.1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.1, Copyright (c) 2002-2018, by Derick Rethans
```
This is a minimal test showing the same issue:
```php
<?php
function test() {
    return true;
}

if ($a = test() && $a) {
    print('test');
}
```
running it results in:
```
$ php test.php 
PHP Notice:  Undefined variable: a in /test/test.php on line 6
PHP Stack trace:
PHP   1. {main}() /test/test.php:0
```

**Comment by soyuka** [comment]
gotcha thanks!

**Comment by teohhanhui** [comment]
It's the same as #800

The fix is correct, but I'll fix the CS.

**Pull request merged**
