### PR TITLE
Fix doc for name conversion

### PR DESCRIPTION
**Pull request by meyerbaptiste**
As mentioned in https://github.com/api-platform/docs/pull/110#issuecomment-249548709 by @teohhanhui, my previous fix was not the good way.
It's now fixed.

### CODE REVIEW

**Comment by dunglas** [comment]
Thanks @meyerbaptiste

**Comment by teohhanhui** [comment]
I'm sorry, but the Symfony Best Practices says the user services should start with `app.`

**Comment by Simperfit** [comment]
It says it should be short as possible and unique :p

**Comment by teohhanhui** [comment]
So what if there's an `ApiBundle` that uses the `api.` prefix? :stuck_out_tongue:

**Comment by Simperfit** [comment]
This happens 💣

**Comment by dunglas** [comment]
@teohhanhui IMO it doesn't hurt because it's just docs :p. But I agree to change it to `app.` anyway to make it consistent with the Symfony doc.

**Pull request merged**
