### PR TITLE
fix: exception for admin in extension

### PR DESCRIPTION
**Pull request by Zowac**
Fix exception for admin in extension

### CODE REVIEW

**Comment by alanpoulain** [comment]
LGTM, you can close your PR on `main`, it will be merged later.

**Review by alanpoulain — APPROVED** [review]

**Comment by Zowac** [comment]
Ping @alanpoulain or @soyuka :D

**Comment by soyuka** [comment]
your commit needs to match the conventional commit format, for example: `docs: allow extension only if admin`

**Comment by alanpoulain** [comment]
Sorry, I was probably tired, the documentation is OK: if the user is an admin, no condition is added to the query and they can see all the offers.

**Pull request closed without merging**
