### PR TITLE
Add new loader_paths option into configuration

### PR DESCRIPTION
**Pull request by digilist**
See api-platform/core#869

### CODE REVIEW

**Comment by digilist** [comment]
Sorry, I did something stupid and deleted my fork too early. It looks like I cannot recover it. Are you able to modify this PR? For example with the following path:

"%kernel.root_dir%/../src/api/user_resources.yml".

Otherwise, I think that I need to submit a new PR.

**Comment by Simperfit** [comment]
@digilist you cou please submit a new PR, i can't edit the file ?

**Comment by dunglas** [comment]
I propose to merge this PR as is and to open a new one with the change suggested by @sroze. We cannot restore the fork either.

**Comment by digilist** [comment]
I opened a new PR.

**Pull request closed without merging**
