### PR TITLE
update to name change

### PR DESCRIPTION
**Pull request by mysiar**

### CODE REVIEW

**Comment by soyuka** [comment]
Might this be on 2.1 branch?

**Comment by mysiar** [comment]
it does only concern client-generator

**Comment by soyuka** [comment]
yes I mean on the 2.x branch of this repository because it's a fix to the current documentation.

**Comment by dunglas** [comment]
It has already been handled in https://github.com/api-platform/docs/pull/271. I just need to merge the branch `2.1` in `master`.

**Pull request closed without merging**
