### PR TITLE
Fix Swagger decorator service

### PR DESCRIPTION
**Pull request by oschwartz**

### CODE REVIEW

**Comment by dunglas** [comment]
Thanks @oschwartz!

**Comment by borNfreee** [comment]
Isn't it a BC break?

**Comment by dunglas** [comment]
It's not at the code level, but indeed it could wdyt @vincentchalamon?

**Comment by dunglas** [comment]
Related to https://github.com/api-platform/api-platform/issues/938#issuecomment-454001663

**Comment by antograssiot** [comment]
isn't that related to Symfony 4.2.2 also and the changes that create issue with data providers etc ? I tried it from the doc recently and I'm pretty sure it was still working.
Decorating the other normlizer is still valid anyway

**Comment by dunglas** [comment]
Good catch, it's probably related. But it means that we should set the priority of our decorator to `-1` or a similar negative value then.

**Comment by dunglas** [comment]
We really need to change the priorities of all our normalizers...

**Comment by guilliamxavier** [comment]
Xref #722

**Pull request merged**
