### PR TITLE
Fix MultipartDecoder to support more denormalization types

### PR DESCRIPTION
**Pull request by cedriclombardot**

### CODE REVIEW

**Comment by alanpoulain** [comment]
I think JSON-encoding the values is way simpler, don't you think so?

**Comment by cedriclombardot** [comment]
Not sure to understand your propposal @alanpoulain ?

**Comment by alanpoulain** [comment]
See https://github.com/api-platform/docs/pull/2065.

**Comment by alanpoulain** [comment]
Closed in favor of https://github.com/api-platform/docs/pull/2065.

**Pull request closed without merging**
