### PR TITLE
feature: add helm dependencies update

### PR DESCRIPTION
**Pull request by Simperfit**

### CODE REVIEW

**Comment by teohhanhui** [comment]
https://docs.helm.sh/helm/#helm-dependency-update
> On successful update, this will generate a lock file that can be used to rebuild the requirements to an exact version.

Shouldn't we check in the lock file?

**Comment by dunglas** [comment]
Thanks @Simperfit. I think we need to add the lock file, indeed.

**Comment by teohhanhui** [comment]
@dunglas The `requirements.lock` file has been added in https://github.com/api-platform/api-platform/pull/666

**Comment by dunglas** [comment]
Do we need to update the docs then?

**Comment by teohhanhui** [comment]
It depends on whether we think it's desirable to have fixed dependencies. I'm not sure it's the right thing to do.

**Pull request merged**
