### PR TITLE
[DEFAULT ORDER] #1246: Support default order for a specific custom operation

### PR DESCRIPTION
**Pull request by ahmed-bhs**

### CODE REVIEW

**Comment by soyuka** [comment]
this should target master as we merged this as a new feature

**Comment by ahmed-bhs** [comment]
@soyuka  done, thank you for your review, it's done, you can check again!

**Comment by ahmed-bhs** [comment]
@soyuka thank you for the review, it's done you can check again.

**Comment by soyuka** [comment]
thanks @ahmed-bhs !

**Pull request merged**
