### PR TITLE
docs: Remove empty string defaults from entities

### PR DESCRIPTION
**Pull request by GaryClarke**
I'm not getting the SQL exception in 'Validating Data' section; empty strings are being stored instead of null being attempted.

The simplest fix is to remove the default empty strings from the entities.

This is using the Symfony and Composer install.

### CODE REVIEW

**Comment by alanpoulain** [comment]
I think it would be better to change only the `title` field by:
```php
public ?string $title = null;
```

**Comment by GaryClarke** [comment]
@alanpoulain works for me...I'll update with this

**Comment by dunglas** [comment]
Allowing null values here is bad DB and entity design IMHO. I would prefer to just change the wording to tell that allowing the user to not fill the title is not what we except, and introduce validation with the `#[NotBlank]` assertion. WDYT?

**Comment by alanpoulain** [comment]
Not sure what you mean Kevin. The resource is not linked yet to DB. The Doctrine attribute can be not nullable but this one needs to be nullable in order to deserialize it correctly and have a `NotBlank` validation on it working as expected.

**Comment by dunglas** [comment]
Exactly!

**Comment by alanpoulain** [comment]
But currently (and sadly?) there is no other way to correctly have validation without using for instance DTOs.

**Comment by dunglas** [comment]
I'm not sure to understand @alanpoulain

**Comment by alanpoulain** [comment]
My bad maybe it works since `null` is not given directly in the input body.
You can leave it like this then but you need to modify the following paragraphs (when linking to Doctrine) @GaryClarke.

**Comment by GaryClarke** [comment]
@alanpoulain good point...done now 👍

**Comment by dunglas** [comment]
I don't think that we must remove the default values (this could trigger "initialized value" exceptions. Couldn't we remove the part about the SQL error and say that sending no values or an empty string doesn't trigger an error while it should?

**Comment by GaryClarke** [comment]
OK...I'll change to that.

**Comment by dunglas** [comment]
Thank you very much @GaryClarke, and sorry for the delay.

**Comment by GaryClarke** [comment]
You're welcome @dunglas 🤝 ..even though I'd totally forgot about this 😂

**Pull request merged**
