### PR TITLE
Remove an option that is not in 2.2

### PR DESCRIPTION
**Pull request by antograssiot**
ref api-platform/api-platform#670

### CODE REVIEW

**Comment by dunglas** [comment]
Can you also open the PR on master to re-add it please?

**Comment by dunglas** [comment]
Thanks!

**Comment by antograssiot** [comment]
Yeah I had it in mind, I'll do that this afternoon @dunglas

**Comment by dkarlovi** [comment]
Wait, is this my fault or what? I targeted the wrong branch in my PR?

**Comment by teohhanhui** [comment]
@dkarlovi It was our fault as `master` was accidentally merged into `2.2` before this. It has since been fixed.

**Pull request merged**
