### PR TITLE
Add "nav.yml"

### PR DESCRIPTION
**Pull request by mauchede**
In the new website (see https://github.com/api-platform/website/pull/16), we will generate the pages from markdown.

To improve navigation, the website will use a file `nav.yml`. In this file, we have to possibility to:
* sort page (instead of rename each file in documentation `001-*`).
* create "virtual" level (for example: `./philosophy.md` will be in `/extra/philosophy`).

### CODE REVIEW

**Comment by mauchede** [comment]
I created a "nav generator": this ([melody](https://github.com/sensiolabs/melody)) script will read `./index.md` and generate `nav.yml`.

@dunglas: Do we have to manage manually `nav.yml` or do you prefer to generate it? If you prefer the second option, do you think this script should be in `api-platform/docs` or in `api-platform/website`?

You can find here, the code of the generator:

```php
<?php
<<<CONFIG
packages:
    - "erusev/parsedown: ^1.6"
    - "symfony/yaml: ^3.2"
CONFIG;

use Symfony\Component\Yaml\Yaml;

$content = file_get_contents(__DIR__ . '/../src/pages/docs/index.md');
$content = str_replace(['`'], ['"'], $content);

$parser = new Parsedown();
$html = new SimpleXMLElement('<root>'.$parser->text($content).'</root>');

function guessPath(SimpleXMLElement $h2): string
{
    $firstItem = $h2->xpath('following-sibling::ol[1]/li[1]')[0];
    $href = $firstItem->a->attributes()['href'];

    if (false === strpos($href, '/')) {
        return 'extra';
    }

    return explode('/', $href)[0];
}

function normalizeAnchors(array $anchors): array
{
    $results = [];
    foreach ($anchors as $anchor) {
        $href = $anchor->a->attributes()['href'];

        $results[] = [
            'id' => explode('#', $href)[1],
            'title' => trim((string) $anchor->a),
        ];
    }

    return $results;
}

function normalizeItems(array $items): array
{
    $results = [];
    foreach ($items as $item) {
        if (empty($item->a)) {
            continue;
        }

        $href = (string) $item->a->attributes()['href'];
        $itemId = false === strpos($href, '/') ? $href : explode('/', $href)[1];
        $itemId = str_replace('.md', '', $itemId);

        $anchors = (array) $item->ol;
        if (!empty($anchors)) {
            $anchors = $anchors['li'];
            if (!is_array($anchors)) {
                $anchors = [$anchors];
            }

            $results[] = [
            'id' => $itemId,
            'title' => trim((string) $item->a),
                'anchors' => normalizeAnchors($anchors),
        ];
        } else {
            $results[] = [
                'id' => $itemId,
                'title' => trim((string) $item->a),
            ];
        }
    }

    return $results;
}

$results = [];
foreach ($html->xpath('//h2') as $h2) {
    $results[] = [
        'title' => (string) $h2,
        'path' => guessPath($h2),
        'items' => normalizeItems($h2->xpath('following-sibling::ol[1]/li'))
    ];
}

file_put_contents(__DIR__ . '/../src/pages/docs/nav.yml', Yaml::dump($results, 6));
```

**Comment by dunglas** [comment]
Automation is always better isn't it :D

**Comment by dunglas** [comment]
I would put this script in the `website` repository. Should this file be edited manually? IMO it shouldn't, so maybe can we not store it here and generate it a build time, wdyt?

**Comment by mauchede** [comment]
I agree. I added this script in `api-platform/website` (see https://github.com/api-platform/website/pull/16).

This PR can be closed.

**Pull request closed without merging**
