### PR TITLE
Update to Træfik V2.0

### PR DESCRIPTION
**Pull request by Darkweak**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tickets       | fixes #953 
| License       | MIT

* Update documentation according to Træfik V2.0
* Lock image to traefik:v2.0
* Add logging
* Link to WorkshopContainous project for full implementation

### CODE REVIEW

**Comment by Darkweak** [comment]
ping @dunglas

**Comment by zspine** [comment]
@Darkweak Exactly!!! The current configuration example is based on v1 and it's not working with the latest image tag! Isn't it better to provide examples for both versions?

**Comment by Darkweak** [comment]
@zspine Sorry for long time inactivity. If you want I've got a repository https://github.com/Darkweak/WorkshopContainous implementing Træfik V2.x then if you're encountering some issues, feel free to ping me.

**Comment by zspine** [comment]
@Darkweak no worries! Thanks a lot for sharing the repository url, I just checked it and contains more detailed configurations. Definitely very helpful.....

Cheers!

**Comment by soyuka** [comment]
Can you rebase? I propose that we merge this.

**Comment by Darkweak** [comment]
Well, this doc is out to date now, I can close this PR and open another one to update the doc when I have the time.

**Comment by dunglas** [comment]
Closing because it's outdated. We must update this docs or remove it.

**Pull request closed without merging**
