### PR TITLE
fix images

### PR DESCRIPTION
**Pull request by Mathieudewet**
Related to: https://github.com/api-platform/website/pull/69 and fix https://github.com/api-platform/website/issues/50

### CODE REVIEW

**Comment by dunglas** [comment]
It doesn’t look good to me: the images must still be displayed correctly on GitHub and when the documentation is downloaded locally.

**Comment by teohhanhui** [comment]
I agree with @dunglas, there should be no changes necessary here. Instead, api-platform/website needs to transform those image paths.

**Comment by teohhanhui** [comment]
Sorry, I misunderstood. I think it should work once we merge. There seems to be a GitHub bug when dealing with branch names with a slash.

**Comment by Mathieudewet** [comment]
Requires rights to make a call to `git remote show git@github.com:api-platform/docs.git`.

**Pull request merged**
