### PR TITLE
Update graphql.md

### PR DESCRIPTION
**Pull request by randriese**
Fixed configuration for multipart/form-data mime-types

### CODE REVIEW

**Comment by alanpoulain** [comment]
Thanks to https://github.com/api-platform/core/blob/af3e3058d01581c7c1a1b384d38dd7a192a64bbc/src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php#L528-L537, both ways are OK. It seems to me the previous is simpler.

**Comment by randriese** [comment]
> Thanks to https://github.com/api-platform/core/blob/af3e3058d01581c7c1a1b384d38dd7a192a64bbc/src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php#L528-L537, both ways are OK. It seems to me the previous is simpler.

the previous one is a lot simpler... however, yesterday I've been looking for a fix for 2 hours because the format provided by the documentation throws an error.

**Comment by alanpoulain** [comment]
Which error?

**Comment by randriese** [comment]
it basically throws a 500 error, stating multipart is not allowed as format when you specify the way that is documented...
I need to check when I get home, as I don't have the project running here now...

**Comment by randriese** [comment]
`{
  "type": "https://tools.ietf.org/html/rfc2616#section-10",
  "title": "An error occurred",
  "detail": "Serialization for the format \"multipart\" is not supported.",
  "trace": [
    {
      "namespace": "",
      "short_class": "",
      "class": "",
      "type": "",
      "function": "",
      "file": "/srv/api/vendor/symfony/serializer/Serializer.php",
      "line": 123,
      "args": []
    },
    {
      "namespace": "Symfony\\Component\\Serializer",
      "short_class": "Serializer",
      "class": "Symfony\\Component\\Serializer\\Serializer",
      "type": "->",
      "function": "serialize",
      "file": "/srv/api/vendor/api-platform/core/src/EventListener/SerializeListener.php",
      "line": 117,
      "args": [
        ["object", "ApiPlatform\\Core\\Api\\Entrypoint"],
        ["string", "multipart"],
        ["array", []]
      ]
    },
    {
      "namespace": "ApiPlatform\\Core\\EventListener",
      "short_class": "SerializeListener",
      "class": "ApiPlatform\\Core\\EventListener\\SerializeListener",
      "type": "->",
      "function": "serializeRawData",
      "file": "/srv/api/vendor/api-platform/core/src/EventListener/SerializeListener.php",
      "line": 69,
      "args": [
        ["object", "Symfony\\Component\\HttpKernel\\Event\\ViewEvent"],
        ["object", "Symfony\\Component\\HttpFoundation\\Request"],
        ["object", "ApiPlatform\\Core\\Api\\Entrypoint"]
      ]
    },
    {
      "namespace": "ApiPlatform\\Core\\EventListener",
      "short_class": "SerializeListener",
      "class": "ApiPlatform\\Core\\EventListener\\SerializeListener",
      "type": "->",
      "function": "onKernelView",
      "file": "/srv/api/vendor/symfony/event-dispatcher/Debug/WrappedListener.php",
      "line": 117,
      "args": [
        ["object", "Symfony\\Component\\HttpKernel\\Event\\ViewEvent"],
        ["string", "kernel.view"],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\EventDispatcher\\Debug",
      "short_class": "WrappedListener",
      "class": "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener",
      "type": "->",
      "function": "__invoke",
      "file": "/srv/api/vendor/symfony/event-dispatcher/EventDispatcher.php",
      "line": 230,
      "args": [
        ["object", "Symfony\\Component\\HttpKernel\\Event\\ViewEvent"],
        ["string", "kernel.view"],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\EventDispatcher",
      "short_class": "EventDispatcher",
      "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
      "type": "->",
      "function": "callListeners",
      "file": "/srv/api/vendor/symfony/event-dispatcher/EventDispatcher.php",
      "line": 59,
      "args": [
        [
          "array",
          [
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ]
          ]
        ],
        ["string", "kernel.view"],
        ["object", "Symfony\\Component\\HttpKernel\\Event\\ViewEvent"]
      ]
    },
    {
      "namespace": "Symfony\\Component\\EventDispatcher",
      "short_class": "EventDispatcher",
      "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
      "type": "->",
      "function": "dispatch",
      "file": "/srv/api/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php",
      "line": 151,
      "args": [
        ["object", "Symfony\\Component\\HttpKernel\\Event\\ViewEvent"],
        ["string", "kernel.view"]
      ]
    },
    {
      "namespace": "Symfony\\Component\\EventDispatcher\\Debug",
      "short_class": "TraceableEventDispatcher",
      "class": "Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher",
      "type": "->",
      "function": "dispatch",
      "file": "/srv/api/vendor/symfony/http-kernel/HttpKernel.php",
      "line": 162,
      "args": [
        ["object", "Symfony\\Component\\HttpKernel\\Event\\ViewEvent"],
        ["string", "kernel.view"]
      ]
    },
    {
      "namespace": "Symfony\\Component\\HttpKernel",
      "short_class": "HttpKernel",
      "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
      "type": "->",
      "function": "handleRaw",
      "file": "/srv/api/vendor/symfony/http-kernel/HttpKernel.php",
      "line": 79,
      "args": [
        ["object", "Symfony\\Component\\HttpFoundation\\Request"],
        ["integer", 1]
      ]
    },
    {
      "namespace": "Symfony\\Component\\HttpKernel",
      "short_class": "HttpKernel",
      "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
      "type": "->",
      "function": "handle",
      "file": "/srv/api/vendor/symfony/http-kernel/Kernel.php",
      "line": 196,
      "args": [
        ["object", "Symfony\\Component\\HttpFoundation\\Request"],
        ["integer", 1],
        ["boolean", true]
      ]
    },
    {
      "namespace": "Symfony\\Component\\HttpKernel",
      "short_class": "Kernel",
      "class": "Symfony\\Component\\HttpKernel\\Kernel",
      "type": "->",
      "function": "handle",
      "file": "/srv/api/public/index.php",
      "line": 28,
      "args": [["object", "Symfony\\Component\\HttpFoundation\\Request"]]
    }
  ]
}
`

**Comment by randriese** [comment]
never mind... it seems the error was thrown because I didn't include the other formats

**Pull request closed without merging**
