### PR TITLE
Update troubleshooting.md

### PR DESCRIPTION
**Pull request by elodieirdor**
Add a little section about a trouble I ran to. Maybe it can help !

### CODE REVIEW

**Comment by dunglas** [comment]
It's probably because you downloaded the `.zip`archive instead of the `.tar.gz`. Some Zip unarchiver doesn't preserve properly the permissions during the extraction process, it's why we suggest to always prefer the zip.

Maybe could you also mention this in the section?

**Comment by dunglas** [comment]
And thanks for contributing btw!

**Comment by teohhanhui** [comment]
While the solution helped in your case, that error message could mean anything. So I'm not really sure we should present it this way...

**Comment by elodieirdor** [comment]
It was a new installation from the github template.

**Comment by dunglas** [comment]
Hum that's weird. How did you retrieved the template's code? Using simply `git clone`? What is your operating system?

**Comment by teohhanhui** [comment]
Yes, the GitHub template feature does not preserve the executable bit, unfortunately. Strangely, a normal fork does.

**Comment by teohhanhui** [comment]
https://github.com/api-platform/api-platform/issues/1164#issuecomment-502753250

**Comment by elodieirdor** [comment]
Indeed @teohhanhui that was my problem!

**Comment by elodieirdor** [comment]
Should I close this PR or do you want me to update the section and mention that the problem occured only with the github template?

**Pull request closed without merging**
