### PR TITLE
Fixes Gherkin books.feature file

### PR DESCRIPTION
**Pull request by renan-taranto**
Related to https://github.com/api-platform/api-platform/issues/197

### CODE REVIEW

**Comment by dunglas** [comment]
First of all, thanks for your fixes! It's really appreciated.

Escaping slashes with backslashes is not mandatory. I would prefer to remove this to make the code more readable. Can you change that please @renan-taranto?

**Comment by renan-taranto** [comment]
@dunglas I forked the Api Platform core, and changed it to stop escaping slashes (https://github.com/renan-taranto/core/tree/patch-1).
The problem is that I'm totally noob on contributing to projects like this. Some guidance on how to properly run it locally so I could run the tests would be much appreciated.

**Comment by dunglas** [comment]
@renan-taranto I'm not sure to understand, the documentation is just a bunch of plain old Markdown files in a separated repo (this one). You can edit them locally using your preferred text editor or directly on GitHub by editing your branch.

But don't worry, I've added a commit directly in your branch and everything is good now. Thanks for your contribution!

**Comment by renan-taranto** [comment]
@dunglas I tought you asked me to change the API Platform core to stop escaping slashes when encoding to json. Alright then.

**Pull request merged**
