### PR TITLE
Fix: Update The Serialization Process Docs.

### PR DESCRIPTION
**Pull request by wilson-ng**
Fix wrong type denormalise,
Fix wrong call decorated method in supportsDenormalization,
Add class property $decorated,
Remove unused import.

### CODE REVIEW

**Comment by dunglas** [comment]
Good catch! Can you rebase  against the 2.1 branch as it’s a bug fix? Thanks!

**Comment by wilson-ng** [comment]
@dunglas i have rebase my branch onto 2.1 and this PR base on 2.1.

**Comment by dunglas** [comment]
Thank you very much!

**Comment by wilson-ng** [comment]
u'r welcome :wink:

**Pull request merged**
