### PR TITLE
Added an advice in the push-relations.md page

### PR DESCRIPTION
**Pull request by Romain**
Symfony HTTP Client is required to make this work.

### CODE REVIEW

**Comment by dunglas** [comment]
This isn't the case. Any client supporting HTTP/2 Server Push (and especially browsers) will support this feature.

**Comment by Romain** [comment]
Hum, interesting...
When I set it up, I got the following error in my logs: `request.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\ClassNotFoundError: "Attempted to load trait "HttpClientTrait" from namespace "Symfony\Component\HttpClient"`.

Searching for a solution, I found [this comment](https://github.com/api-platform/api-platform/issues/1437#issuecomment-592522041) which solved the issue, hence my PR.

**Comment by dunglas** [comment]
This error is probably not related to this feature. Are you using the test client? The test clients needs HttpClient.

**Comment by Romain** [comment]
I'm not using it, but perhaps is it installed by default?
The weird thing is that this error appeared exactly when I set up the push relations.
How can I check if the test client is used? What's the name of the package?

**Comment by dunglas** [comment]
Closing because I'm sure this component isn't needed to use this feature. It's probably a side effect related to a code segment triggered by the push. If the problem persist, please fill an issue on `api-platform/core`.

**Pull request closed without merging**
