### PR TITLE
add php in front of the bin/console command

### PR DESCRIPTION
**Pull request by schmanat**
As I read this chapter the first time, I wondered why it didn't work. A few moments I realized that the console is also an PHP application.

### CODE REVIEW

**Comment by soyuka** [comment]
Hmm what's your OS? `bin/console` is an executable with the correct shebang so it should use `php`.

**Comment by schmanat** [comment]
Hmm Ok, I didn't knew that. I'm using Ubuntu 16.04 with PHP7.1 provided by [Ondrey](https://launchpad.net/~ondrej/+archive/ubuntu/php).

**Comment by schmanat** [comment]
Whats the right permissions for bin/console? After I chmod +x bin/console I could execute the console without php in front.

**Comment by soyuka** [comment]
```
/usr/bin/env php --version
```

Does this work?

**Comment by schmanat** [comment]
Yes it works.

**Comment by schmanat** [comment]
Thx again for your answer, i close this pull request, because it seems that its a missconfiguration of my server setup.

**Pull request closed without merging**
