### PR TITLE
Sync admin's docs with the last version (React Admin)

### PR DESCRIPTION
**Pull request by dunglas**

### CODE REVIEW

**Comment by init-penguin** [comment]
It seems that you've missed `authClient={authClient}` -> `authProvider={authProvider}`

**Comment by dunglas** [comment]
Good catch @init-penguin, fixed

**Comment by init-penguin** [comment]
Sorry to point this again, @dunglas, but i think you forgot about the import statement :)
Now it imports the `authClient` while exporting `HydraAdmin` with `authProvider`, thus you should either change the import to `import authProvider` thing (and filename for consistency too), or change the export of App.js to `authProvider={authClient}`

**Comment by dunglas** [comment]
I'm not sure we need to update the the filename. The React Admin team changed the name of the property to highlight it can be other things than an API client (I guess), but they haven't updated the name of their own clients (for instance the REST client is still called "restClient"). It's why I've not renamed the file and updated the import. But I'm not sure about this.

@fzaninotto, do you have a hint regarding the naming best practice?

**Comment by fzaninotto** [comment]
We try to use "provider" everywhere to avoid confusion. If you found some mentions of `restClient`, that's a mistake on our side. I'll look into the remaining mentions of pre-2.0 terminology.

**Pull request merged**
