### PR TITLE
feat(serialisation): return collection property as IRI

### PR DESCRIPTION
**Pull request by GregoireHebert**
see: https://github.com/api-platform/core/pull/5675

### CODE REVIEW

**Comment by soyuka** [comment]
can you create a guide for it at https://github.com/api-platform/core/tree/main/docs/guides instead ?

**Comment by GregoireHebert** [comment]
instead, or in addition to?
but sure.

**Comment by soyuka** [comment]
instead of

**Comment by GregoireHebert** [comment]
I tried to write a guide in the PR itself.

**Pull request closed without merging**
