### PR TITLE
Fixed typos on Heroku setup page

### PR DESCRIPTION
**Pull request by mickaelandrieu**

### CODE REVIEW

**Comment by soyuka** [comment]
thanks, can you rebase against 2.1?

**Comment by dunglas** [comment]
Merged in c6b4e7031f301487af6f81aceb1777f68b773027. Thanks @mickaelandrieu!

**Comment by mickaelandrieu** [comment]
> thanks, can you rebase against 2.1?

I don't understand: do you want me to do the same pr, but into the `2.1` branch?

**Comment by soyuka** [comment]
np @dunglas  did it manually ;)

**Pull request closed without merging**
